spring:
  banner:
    charset: UTF-8
    location: classpath:banner.txt
  datasource:
    url: jdbc:mysql://localhost:3306/sky-takeout?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver


application:
  name: sky-take-out
  version: 1.0.0

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: fun.kmoon.entity,fun.kmoon.dto,fun.kmoon.vo


knife4j:
  enable: true
  setting:
    language: zh_cn