application:
  name: sky-take-out
  version: 1.0.0
  description: 苍穹外卖
  author: kmoon

spring:
  banner:
    charset: UTF-8
    location: classpath:banner.txt
  datasource:
    url: jdbc:mysql://mysql2.sqlpub.com:3307/sky-takeout?useSSL=false&serverTimezone=UTC
    username: sky_takeout
    password: be95NFYr2LZxduhg
    driver-class-name: com.mysql.cj.jdbc.Driver
#  data:
#    redis:
#      host:
#      port: 6379
#      password:
#      database: 0
#      timeout: 10000

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: fun.kmoon.entity
  configuration:
    map-underscore-to-camel-case: true

knife4j:
  enable: true
  setting:
    language: zh_cn